FROM python:3.11

WORKDIR /src

COPY ./src /src
COPY ./deployments /src/deployments
RUN pip install --no-cache-dir -r requirements.txt


CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]